### Login
POST http://127.0.0.1:5000/auth HTTP/1.1
content-type: application/json

{
    "username": "a",
    "password": "a"
}

### Register User
POST http://127.0.0.1:5000/user HTTP/1.1
content-type: application/json

{
    "username": "2112",
    "password": "1212",
    "email": "aasa@gmasdail.com"
}

### Get Specific Users
GET http://127.0.0.1:5000/user/8 HTTP/1.1

### Get All Users
GET http://127.0.0.1:5000/users HTTP/1.1